### ISSUE TITLE
pack colors =true, still includes rgb file

### ISSUE THREAD

**Issue by GISnick** [unitycoder/PointCloudConverter#21]
When using color packing, it works but the output folder also generates the rgb files which i think are unnecessary.

I noticed older versions would omit the rgb file when color packing is used.

In recent versions both color packing true or false seems to generate the same sized folder because the extra rgb files are still created. I made a test and deleted the rgb files it made and the packed cloud still renders with color properly.

**Comment by unitycoder** [comment]
found it, try latest build:
https://github.com/unitycoder/PointCloudConverter/releases/tag/34
