### ISSUE TITLE
Add Exit code to application

### ISSUE THREAD

**Issue by GISnick** [unitycoder/PointCloudConverter#29]
Adding an exit code to the application would help when calling from command line so you know if it completed successfully

https://stackoverflow.com/questions/155610/how-do-i-specify-the-exit-code-of-a-console-application-in-net

https://en.wikipedia.org/wiki/Exit_status

**Comment by unitycoder** [comment]
any ideas:
If its running batch conversion and single file fails, what should the exitcode be? 
(since it completed successfully. but missed one file..)

or maybe there is (or can define custom) exitcode for partial success?
https://learn.microsoft.com/en-us/windows/win32/debug/system-error-codes

**Comment by GISnick** [comment]
not sure, maybe:
0: success
1: fail
2: partial success, (processed lidar but not all files?)

**Comment by unitycoder** [comment]
these are added to recent builds, can comment if missing from some output.
