### ISSUE TITLE
some las files return 0 points

### ISSUE THREAD

**Issue by unitycoder** [unitycoder/PointCloudConverter#9]
if export *.LAS/LAZ 1.3/1.4 from CloudCompare, returns 0 points
if export *.LAS/LAZ from CloudCompare, this file works

**Comment by yuhe0925** [comment]
same here, the converted las file have 0 bytes

**Comment by unitycoder** [comment]
ok, last time i didn't find the cause yet, but sounds like its some header offset difference between those las versions..

from which tool your las file is coming from?

**Comment by unitycoder** [comment]
same issue with:
- v1.4 format 6
- v1.4 format 7
- v1.2 format 3

**Comment by unitycoder** [comment]
tested v1.4 format 6 in updated laszip, seems to work.

will post update soon, if nothing else breaks.

**Comment by unitycoder** [comment]
available after release 55
